table Medidas
	lineageTag: 19f5e569-6697-4098-a9de-6546d450f9ab

	measure Revenue = SUMX(fact_orders, fact_orders[unidades]*COALESCE(fact_orders[peso],1)*RELATED(dim_productos[precio_producto]))
		lineageTag: b6854789-20f8-4a63-b39f-7e0a3b6634d4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Medidas = m
		mode: import
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Columna1 = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Columna1", type text}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado",{"Columna1"})
				in
				    #"Columnas quitadas"

	annotation PBI_ResultType = Table

